[build]
  command = "npm run build"
  functions = "dist"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main"
  status = 200

[functions]
  node_bundler = "esbuild" 